apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      nodeSelector:
        app: kafka1
      containers:
      - name: kafka1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: AWS_LOAD_BALANCER_DNS_OF_WORKER_NODE_1
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      nodeSelector:
        app: kafka2
      containers:
      - name: kafka2
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: AWS_LOAD_BALANCER_DNS_OF_WORKER_NODE_2
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kafka3
spec:
  replicas: 1
  selector:
    matchLabels:    
      app: kafka3
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      nodeSelector:
        app: kafka3
      containers:
      - name: kafka3
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: AWS_LOAD_BALANCER_DNS_OF_WORKER_NODE_3
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181,zoo2:2181,zoo3:2181